### ISSUE TITLE
Timers not working! D:

### ISSUE THREAD

**Issue by mbtuchman** [jayrox/destinyeventtracker.com#1]
Timers are off on earth

**Comment by mandlar** [comment]
Can you provide some more information? Which event timers? How much of a difference are you seeing?

**Comment by mbtuchman** [comment]
They are anywhere from 13-17 min off.

Only in The Steppes.

**Comment by mbtuchman** [comment]
I'd be happy to help with the project! :smile:

**Comment by jayrox** [comment]
early or late? do you have examples of actual arrival times?

**Comment by mbtuchman** [comment]
neither. 

It's not even arriving

**Comment by mbtuchman** [comment]
(meaning it's REALLY far off )

**Comment by mandlar** [comment]
The Steppe's event is rare, it isn't always guaranteed to happen. When I do my public event runs, I _might_ see it happen once in a couple of hours.

**Comment by mbtuchman** [comment]
Ahh Okay xD

**Comment by mbtuchman** [comment]
As I said earlier, I'd be happy to help out with the project!
If you're up for it, email me: me@mbtuchman.com

**Comment by jayrox** [comment]
steppes is apparently a pretty rare event. based on what i can find on it the start times are H:15-H:30& H:40-H:55

if you do happen to catch the event, mark down the time somewhere. i'd be more than happy to adjust the timers for accuracy.

**Comment by jayrox** [comment]
the project is completely open source. 100% is right here on github. feel free to make suggestions, pull requests for fixes, improvements and @mandlar and I will looked them over.

**Comment by mbtuchman** [comment]
Awesome!
